# Generated by Django 4.1.7 on 2023-02-20 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^.{3}$')])),
                ('sub_code', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^.{3}$')])),
                ('quest_code', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 5', regex='^.{5}$')])),
                ('difficulty_code', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 1', regex='^.{1}$')])),
                ('quest', models.CharField(max_length=500)),
                ('options', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=500)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaiib.question')),
            ],
        ),
    ]
