# Generated by Django 4.1.7 on 2023-02-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
