# Generated by Django 4.1.7 on 2023-02-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jaiib', '0006_remove_brainjaiib_course_cod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainjaiib',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
