# Generated by Django 4.1.7 on 2023-02-22 16:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0009_remove_profile_course_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_cod',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 3', regex='^.{3}$')]),
        ),
        migrations.AlterField(
            model_name='brainjaiib',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jaiib.profile'),
        ),
    ]
