# Generated by Django 4.1.7 on 2023-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0010_profile_course_cod_alter_brainjaiib_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainjaiib',
            name='profile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
