# Generated by Django 4.1.7 on 2023-03-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0016_remove_question_correct_remove_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='quest',
        ),
    ]
