# Generated by Django 4.1.7 on 2023-03-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0017_rename_question_answer_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quest',
            new_name='question',
        ),
    ]
