# Generated by Django 4.1.7 on 2023-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0019_question_correct_question_options_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct',
            new_name='option3_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1_correct',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_correct',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
