# Generated by Django 4.1.7 on 2023-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0020_rename_correct_question_option3_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2_correct',
            field=models.BooleanField(default=False),
        ),
    ]
