# Generated by Django 4.1.7 on 2023-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaiib', '0021_alter_question_option1_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
