# Generated by Django 4.1.7 on 2023-02-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_brainjaiib_course_cod_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainjaiib',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brain', to='user.profile'),
        ),
    ]
