# Generated by Django 4.1.7 on 2023-02-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_brainjaiib_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainjaiib',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='user.profile'),
        ),
    ]
